-- =============================================================================
-- SAN-1404 · Seeded Medellín new-project dataset — data contract + provenance + RLS
-- Run with: supabase test db
-- =============================================================================

begin;

select plan(28);

-- ── dataset contract ─────────────────────────────────────────────────────────
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park'])), 10, 'A1 exactly 10 seeded projects');
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and ownership_status <> 'unclaimed'), 0, 'A2 every seeded project is unclaimed');
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and partner_id is not null), 0, 'A3 no seeded project has a partner_id');
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and publish_state <> 'published'), 0, 'A4 every seeded project is published');
select is((select count(*)::int from public.development_projects p where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and not exists (select 1 from public.development_project_sources s where s.project_id = p.id)), 0, 'A5 every seeded project has provenance');

-- ── provenance is a fact, not now() ──────────────────────────────────────────
select is((select count(*)::int from public.development_project_sources s join public.development_projects p on p.id = s.project_id where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and s.checked_at is null), 0, 'A6 every source has a checked_at timestamp');
select is((select count(*)::int from public.development_project_sources s join public.development_projects p on p.id = s.project_id where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and s.http_status is distinct from 200), 0, 'A7 every source returned HTTP 200');
select is((select count(*)::int from public.development_project_sources s join public.development_projects p on p.id = s.project_id where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and s.scope <> 'project'), 0, 'A8 every source is project-scoped');
select is((select count(*)::int from public.development_project_sources s join public.development_projects p on p.id = s.project_id where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and s.checked_at::date <> date '2026-10-06'), 0, 'A9 every source was checked on the research date');
select is((select count(*)::int from public.development_project_sources s join public.development_projects p on p.id = s.project_id where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and s.source_url like '%zonario.co%' and s.source_updated_at::date = date '2026-09-26'), 2, 'A10 Zonario sources carry the source_updated_at the page states');

-- ── primary source ───────────────────────────────────────────────────────────
select is((select count(*)::int from public.development_projects p where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and p.publish_state = 'published' and p.primary_source_id is null), 0, 'A11 every published project has a primary source');
select is((select count(*)::int from public.development_projects p where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and p.primary_source_id is not null and not exists (select 1 from public.development_project_sources s where s.id = p.primary_source_id and s.project_id = p.id)), 0, 'A12 the primary source belongs to its project');

-- ── unit types: scoped to SAN-1404 and correctly attributed ──────────────────
select is((select count(*)::int from public.development_unit_types u join public.development_projects p on p.id = u.project_id where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park'])), 18, 'A13 the verified unit-type set is present');
select is((select count(*)::int from public.development_unit_types u join public.development_projects p on p.id = u.project_id where p.source_key = 'medellin:new-project:distrito-33' and u.source_kind = 'marketplace'), 1, 'A14 Distrito 33 unit is attributed to a marketplace source');
select is((select count(*)::int from public.development_unit_types u join public.development_projects p on p.id = u.project_id where p.source_key = 'medellin:new-project:vigo' and u.source_kind = 'marketplace'), 1, 'A15 Vigo unit is attributed to a marketplace source');
select is((select count(*)::int from public.development_unit_types u join public.development_projects p on p.id = u.project_id where p.source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and u.source_url not like '%tulugar.com%' and u.source_kind <> 'developer'), 0, 'A16 every non-marketplace unit is attributed to a developer source');

-- ── numeric + identity invariants ────────────────────────────────────────────
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and price_from_cents is not null and price_from_cents <= 0), 0, 'A17 no non-positive price');
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and price_from_cents is not null and price_to_cents is not null and price_to_cents < price_from_cents), 0, 'A18 no inverted price range');
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and ((latitude is null) <> (longitude is null))), 0, 'A19 coordinates are a pair or both null');
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and publish_state = 'published' and verified_at is null), 0, 'A20 published projects have verified_at');
select is((select count(distinct slug)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park'])), 10, 'A21 every seeded project has a unique slug');
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park']) and ownership_status = 'claimed'), 0, 'A22 no seeded project is claimed');

-- ── idempotency is structural: the ON CONFLICT targets are unique keys ───────
select is((select count(*)::int from pg_constraint where conrelid = 'public.development_projects'::regclass and contype = 'u' and pg_get_constraintdef(oid) ilike '%(source_key)%'), 1, 'A23 development_projects.source_key is unique');
select is((select count(*)::int from pg_constraint where conrelid = 'public.development_project_sources'::regclass and contype = 'u' and pg_get_constraintdef(oid) ilike '%(project_id, source_url)%'), 1, 'A24 sources(project_id, source_url) is unique');
select is((select count(*)::int from pg_constraint where conrelid = 'public.development_unit_types'::regclass and contype = 'u' and pg_get_constraintdef(oid) ilike '%(project_id, source_key)%'), 1, 'A25 unit types(project_id, source_key) is unique');

-- ── RLS behavior on the seeded inventory ─────────────────────────────────────
set local role anon;
select set_config('request.jwt.claim.sub', '', true);
select is((select count(*)::int from public.development_projects where source_key = any(array['medellin:new-project:nexus', 'medellin:new-project:distrito-33', 'medellin:new-project:grand-coral', 'medellin:new-project:nutibara-parkway', 'medellin:new-project:vigo', 'medellin:new-project:arrayan', 'medellin:new-project:saman', 'medellin:new-project:guayacanes', 'medellin:new-project:palma', 'medellin:new-project:river-park'])), 10, 'A26 anon reads the published seeded projects');
select throws_ok(
  $$insert into public.development_projects (source_key, slug, name, publish_state, verified_at)
    values ('san1404-anon', 'san1404-anon', 'Anon', 'draft', now())$$,
  '42501', null, 'A27 anon cannot write seeded inventory');

reset role;
set local role authenticated;
-- The JWT subject below is an arbitrary UUID. It is only read via
-- set_config('request.jwt.claim.sub', ...) by auth.uid(); it does not need a
-- matching auth.users row. It intentionally has no partner_members row, so RLS denies.
select set_config('request.jwt.claim.sub', 'e1404000-0000-4000-8000-000000000001', true);
with u as (
  update public.development_projects set name = name
  where source_key = 'medellin:new-project:nexus'
  returning 1
)
select set_config('san1404.auth_updated', count(*)::text, true) from u;
select is(current_setting('san1404.auth_updated')::int, 0, 'A28 authenticated non-member cannot mutate seeded inventory');
reset role;

select * from finish();
rollback;
